kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: raghuveerk/python-world
    tags: 
    - 1.0.1
    - ${DRONE_COMMIT_SHA:0:7} 
    - latest 
    username:
     from_secret: docker_username
    password:
     from_secret: docker_password
  
  
